[book]
authors = ["Felienne Hermans", "Rico Hermans", "Daan van Berkel"]
language = "en"
multilingual = false
src = "src"
title = "Crochet Workshop"

[output.html]
mathjax-support = true
additional-css = ["custom.css"]
